services:
  macos:
    image: ghcr.io/ehsidawi/my-macos:edge
    container_name: macos
    environment:
      VERSION: "${MACOS_VERSION:-15}"
      RAM_SIZE: "${RAM_SIZE:-4G}"
      CPU_CORES: "${CPU_CORES:-1}"
      DISK_SIZE: "${DISK_SIZE:-64G}"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    expose:
      - "8006"
    volumes:
      - ./macos:/storage
    restart: unless-stopped
    stop_grace_period: 2m

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: macos-cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - macos
    restart: unless-stopped
